spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      file-size-threshold: 2KB
      max-file-size: 200MB
  datasource:
    url: jdbc:h2:mem:recipe;DATABASE_TO_UPPER=false
    username: sa
    password: abc123
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: local # change to 'prod' to apply the configuration in application-prod.yml
springdoc:
  api-docs:
    path: /er-docs
site:
  urls:
    base-url: "http://localhost:13011"
  app:
    jwtSecret: johnnySecretKey
    jwtExpirationMs: 86400000
server:
  port: 13011