spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe
    username: sa
    password: abc123
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
site:
  urls:
    base-url: "http://localhost:13011"